### ISSUE TITLE
start script not working as is

### ISSUE THREAD

**Issue by ggcaponetto** [dynamicstrategies/cardano-wallet-connector#10]
The start script fails with the following error trace of node's GC.

I was only able to run it via ``react-scripts --max_old_space_size=8186 start``.

Is this something to be mentioned in a troubleshooting section? I find this repo so useful for newcomers like me.

**Comment by jsyme222** [comment]
This is me mentioned in the README.

**Comment by ggcaponetto** [comment]
Thanks. Didn't look good enogh. Sorry!
