### ISSUE TITLE
Does not work as is

### ISSUE THREAD

**Issue by marcoarroyo41** [dynamicstrategies/cardano-wallet-connector#2]
Hello, 

When I clone the repo, change directory into it, and npm install && npm start I get the following error.  It does not seem to work as is, do I need to update any files?

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF69B3B7B7F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+114079
 2: 00007FF69B344546 DSA_meth_get_flags+65542
 3: 00007FF69B3453FD node::OnFatalError+301
 4: 00007FF69BC7B29E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF69BC6587D v8::SharedArrayBuffer::Externalize+781
 6: 00007FF69BB08C4C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
 7: 00007FF69BB05D64 v8::internal::Heap::CollectGarbage+4244
 8: 00007FF69BB036E0 v8::internal::Heap::AllocateExternalBackingStore+2000
 9: 00007FF69BB28266 v8::internal::Factory::NewFillerObject+214
10: 00007FF69B85A735 v8::internal::DateCache::Weekday+1797
11: 00007FF69BD08F91 v8::internal::SetupIsolateDelegate::SetupHeap+494417
12: 0000021900C1F2A0

**Comment by dshibaev** [comment]
Hi,

This is normally cause by insufficient memory

Try running `export NODE_OPTIONS="--max-old-space-size=8192"` before running `npm start`

**Comment by marcoarroyo41** [comment]
I'm doing this in PowerShell in a Windows 10 VM with 32gb of RAM.  Should I theoretically be able to just git clone the repo, cd into the folder, npm install and npm start run and it just work as is?

**Comment by dynamicstrategies** [comment]
There is a good discussion about this on stackexchange if you want to get
into the details:

https://stackoverflow.com/questions/53230823/fatal-error-ineffective-mark-compacts-near-heap-limit-allocation-failed-javas

The package that causes the error is the cardano-serialization-lib btw

Try if running the suggested command removes the error. I have added it to
the troubleshooting section in the Readme

**Comment by marcoarroyo41** [comment]
I switched to Linux and ran that command, different error this time haha.  Is there any other configuration required or any commands besides just downloading the repo and npm install and start run?



Html Webpack Plugin:
  Error: Child compilation failed:
  Module.createRequire is not a function
  
  - child-compiler.js:169 childCompiler.runAsChild
    [cardano-wallet-connector]/[html-webpack-plugin]/lib/child-compiler.js:169:1    8
  
  - Compiler.js:564 compile
    [cardano-wallet-connector]/[webpack]/lib/Compiler.js:564:11
  
  - Compiler.js:1183 hooks.afterCompile.callAsync.err
    [cardano-wallet-connector]/[webpack]/lib/Compiler.js:1183:17
  
  
  - Hook.js:18 Hook.CALL_ASYNC_DELEGATE [as _callAsync]
    [cardano-wallet-connector]/[tapable]/lib/Hook.js:18:14
  
  - Compiler.js:1179 compilation.seal.err
    [cardano-wallet-connector]/[webpack]/lib/Compiler.js:1179:33
  
  - Compilation.js:2784 finalCallback
    [cardano-wallet-connector]/[webpack]/lib/Compilation.js:2784:11
  
  - Compilation.js:3089 hooks.afterSeal.callAsync.err
    [cardano-wallet-connector]/[webpack]/lib/Compilation.js:3089:11
  
  
  - Hook.js:18 Hook.CALL_ASYNC_DELEGATE [as _callAsync]
    [cardano-wallet-connector]/[tapable]/lib/Hook.js:18:14

**Comment by marcoarroyo41** [comment]
I upgraded to Nodejs version 14 and that fixed it!

**Comment by dshibaev** [comment]
Great!

I've also updated the Readme that requires Nodejs version 14 or higher
