### ISSUE TITLE
Send ADA give error some times.

### ISSUE THREAD

**Issue by hussamBim** [dynamicstrategies/cardano-wallet-connector#3]
HI, 
I get this issue frequently when i send ADA to some address.
Uncaught (in promise) Not enough ADA leftover to include non-ADA assets in a change address

**Comment by dshibaev** [comment]
Hi,

This is related to how available UTXOs are selected from your wallet.

First make sure that you have enough ADA in your wallet and then try changing the "strategy" number in this part of the code `txBuilder.add_inputs_from(txUnspentOutputs, 1)` which determines how it selects available UTXOs from your wallet. The options are `1` for LargestFirst, `2` for RandomImprove, `3` for LargestFirstMultiAsset and `4` for RandomImproveMultiAsset

**Comment by hussamBim** [comment]
Hi @dshibaev its working. Thanks for your reply.
