### ISSUE TITLE
Errors on npm start

### ISSUE THREAD

**Issue by Reaziii** [dynamicstrategies/cardano-wallet-connector#4]
<img width="1214" alt="Screenshot 2022-04-13 at 3 43 04 PM" src="https://user-images.githubusercontent.com/45226278/163148426-16b121c5-05cc-4bb8-8fe3-faeae8b7427b.png">

**Comment by dshibaev** [comment]
Please see the Troubleshooting section of the docs , to fix the error do
the following


   - If you get an error that starts with FATAL ERROR: Reached heap limit
   Allocation failed - JavaScript heap out of memory ... then run this export
   NODE_OPTIONS="--max-old-space-size=8192" before running npm start

**Comment by dshibaev** [comment]
The error gets solved by running NODE_OPTIONS="--max-old-space-size=8192"
Documented in the troubleshooting section
