### ISSUE TITLE
Mint with multi-admin Policy ID

### ISSUE THREAD

**Issue by hussamBim** [dynamicstrategies/cardano-wallet-connector#7]
Hi, I have policy id that can mint from multiple admins. can you give a way around we can sign mint NFT transaction from admin and user account simultaneously from react side.

**Comment by dynamicstrategies** [comment]
Sounds like you need to sign the transaction by multiple users.
Try looking at this part of the code which requests the user to sign the transaction in `App.js`

```
        let txVkeyWitnesses = await this.API.signTx(Buffer.from(tx.to_bytes(), "utf8").toString("hex"), true);
        txVkeyWitnesses = TransactionWitnessSet.from_bytes(Buffer.from(txVkeyWitnesses, "hex"));

        transactionWitnessSet.set_vkeys(txVkeyWitnesses.vkeys());

        const signedTx = Transaction.new(
            tx.body(),
            transactionWitnessSet
        );
```

**Comment by hussamBim** [comment]
Yes, exactly i need that but owner is created from cardano-cli i have skey and user will sign it using its nami wallet. And can you please provide some reference how i can create mint NFT body as well using your repo. I have done all in backend using cardanocli-js. I have policy id generated from cli.

**Comment by dynamicstrategies** [comment]
Take a look at an example here for minting NFTs with the serialization lib:

https://github.com/Emurgo/cardano-serialization-lib/blob/master/doc/getting-started/minting-nfts.md

**Comment by hussamBim** [comment]
> Take a look at an example here for minting NFTs with the serialization lib:
> 
> https://github.com/Emurgo/cardano-serialization-lib/blob/master/doc/getting-started/minting-nfts.md

HI, thanks for your help. I have one issue left how, I can use policy id and skey, vkey made from cli in cardano-serialization-lib-node. I
